name = "fix-it-temp"
compatibility_date = "2024-09-23"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "fibi-db"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "db/migrations"

[[r2_buckets]]
binding = "RAW_PAYLOADS"
bucket_name = "fibi-raw-payloads"
