import { sqliteTable, text } from 'drizzle-orm/sqlite-core';

export const stagingInbox = sqliteTable('staging_inbox', {
    id: text('id').primaryKey(), // UUID generated by the app
    leadName: text('lead_name').notNull(),
    leadEmail: text('lead_email').notNull(),
    leadPhone: text('lead_phone').notNull(),
    r2PayloadKey: text('r2_payload_key').notNull(), // S3/R2 object key containing the massive JSON arrays
    status: text('status').notNull().default("PENDING_REVIEW"), // PENDING_REVIEW, APPROVED, ARCHIVED
    createdAt: text('created_at').notNull(), // ISO Timestamp string
});
